/**
 * Code Generator Worker - AI-powered code generation
 *
 * Features:
 * - Generate Theia extensions
 * - Generate Godot scenes
 * - Quality selector (fast/cheap → slow/premium)
 * - Work ratio transparency
 * - Verification + rollback
 */

// Simple ID generator
function nanoid(): string {
  const chars = '0123456789abcdefghijklmnopqrstuvwxyz';
  let result = '';
  for (let i = 0; i < 16; i++) {
    result += chars[Math.floor(Math.random() * chars.length)];
  }
  return result;
}

// ═══════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════

export type QualityLevel = 'fast' | 'balanced' | 'premium';

export interface GenerationRequest {
  type: 'theia-extension' | 'godot-scene' | 'worker' | 'component';
  prompt: string;
  quality: QualityLevel;
  context?: Record<string, any>;
}

export interface GenerationResult {
  id: string;
  type: string;
  prompt: string;
  quality: QualityLevel;
  model_used: string;
  tokens_generated: number;
  work_ratio: number;
  code: string;
  files: GeneratedFile[];
  verified: boolean;
  rollback_id?: string;
  created_at: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

export interface VerificationResult {
  passed: boolean;
  errors: string[];
  warnings: string[];
  tests_run: number;
  tests_passed: number;
}

// ═══════════════════════════════════════════════════════════
// Model Configuration
// ═══════════════════════════════════════════════════════════

export const MODEL_CONFIGS: Record<QualityLevel, {
  model: string;
  maxTokens: number;
  temperature: number;
  expectedWorkRatio: number;
}> = {
  fast: {
    model: 'claude-3-5-haiku-20241022',
    maxTokens: 4096,
    temperature: 0.7,
    expectedWorkRatio: 0.6  // AI does ~60% of work
  },
  balanced: {
    model: 'claude-3-5-sonnet-20241022',
    maxTokens: 8192,
    temperature: 0.5,
    expectedWorkRatio: 0.75  // AI does ~75% of work
  },
  premium: {
    model: 'claude-3-5-opus-20241022',
    maxTokens: 16384,
    temperature: 0.3,
    expectedWorkRatio: 0.85  // AI does ~85% of work
  }
};

// ═══════════════════════════════════════════════════════════
// Code Templates (exported for documentation/testing)
// ═══════════════════════════════════════════════════════════

export const THEIA_EXTENSION_TEMPLATE = `/**
 * {{DESCRIPTION}}
 * Generated by StudyLoG.AI Code Generator
 * Model: {{MODEL}}
 * Work Ratio: {{WORK_RATIO}} (AI contribution)
 */

import { injectable, inject } from '@theia/core/shared/inversify';
import { Widget } from '@theia/core/lib/browser/widgets/widget';
import { FrontendApplicationContribution } from '@theia/core/lib/browser/frontend-application';

@injectable()
export class {{CLASS_NAME}}Widget extends Widget {
    static readonly ID = '{{PACKAGE_NAME}}:widget';
    static readonly LABEL = '{{LABEL}}';

    constructor(
        @inject(FrontendApplicationContribution) protected readonly app: FrontendApplicationContribution
    ) {
        super();
        this.id = {{CLASS_NAME}}Widget.ID;
        this.title.label = {{CLASS_NAME}}Widget.ID;
        this.title.caption = {{CLASS_NAME}}Widget.LABEL;
        this.title.iconClass = 'fa fa-' + this.getIcon();
        this.title.closable = true;
    }

    protected getIcon(): string {
        return 'puzzle-piece';  // Font Awesome icon
    }

    protected onActivateRequest(msg: Message): void {
        super.onActivateRequest(msg);
        // TODO: Implement widget activation
    }

    protected render(): React.ReactNode {
        return (
            <div className="{{PACKAGE_NAME}}-container">
                <h1>{this.title.label}</h1>
                <p>{{DESCRIPTION}}</p>
                {/* TODO: Add your UI here */}
            </div>
        );
    }
}
`;

export const GODOT_SCENE_TEMPLATE = `[gd_scene load_steps=2 format=3 uid="uid://{{UID}}"]

[ext_resource type="Script" path="res://{{SCRIPT_NAME}}.gd" id="1_{{ID}}"]

[node name="Root" type="Node2D"]
script = ExtResource("1_{{ID}}")

[node name="Label" type="Label" parent="."]
offset_left = 20.0
offset_top = 20.0
offset_right = 300.0
offset_bottom = 50.0
text = "{{LABEL}}"
horizontal_alignment = 1
`;

export const GODOT_SCRIPT_TEMPLATE = `extends Node2D

# {{DESCRIPTION}}
# Generated by StudyLoG.AI Code Generator
# Model: {{MODEL}}
# Work Ratio: {{WORK_RATIO}} (AI contribution)

signal {{SIGNAL_NAME}}_completed(value)

var _data: Dictionary = {}

func _ready() -> void:
    print("{{CLASS_NAME}} initialized")
    # TODO: Add initialization logic

func _process(delta: float) -> void:
    # TODO: Add per-frame logic
    pass

func {{FUNCTION_NAME}}() -> void:
    """{{DESCRIPTION}}"""
    # TODO: Implement this function
    {{SIGNAL_NAME}}_completed.emit(true)
`;

// ═══════════════════════════════════════════════════════════
// Prompt Builders
// ═══════════════════════════════════════════════════════════

function buildTheiaExtensionPrompt(prompt: string): string {
  return `You are an expert Theia extension developer. Generate a complete, working Theia extension based on the user's request.

User Request:
${prompt}

Requirements:
1. Generate a complete frontend module with widget
2. Include proper inversify bindings
3. Add a browser module contribution
4. Include CSS styles
5. Follow Theia best practices
6. Make the UI clean and functional

Response format: Return a JSON object with this structure:
{
  "description": "Brief description",
  "packageName": "kebab-case-name",
  "className": "PascalCaseName",
  "label": "Display Label",
  "files": [
    {
      "path": "src/browser/extension.ts",
      "content": "full file content",
      "language": "typescript"
    }
  ]
}`;
}

function buildGodotScenePrompt(prompt: string): string {
  return `You are an expert Godot 4.3 developer. Generate a complete, working Godot scene based on the user's request.

User Request:
${prompt}

Requirements:
1. Generate a .tscn scene file
2. Generate the accompanying .gd script
3. Use GDScript 2.0 syntax
4. Include proper signal handling
5. Add helpful comments
6. Make the scene functional and testable

Response format: Return a JSON object with this structure:
{
  "description": "Brief description",
  "sceneName": "kebab-case-name",
  "className": "PascalCaseName",
  "files": [
    {
      "path": "scene_name.tscn",
      "content": "full scene file content",
      "language": "gdscene"
    },
    {
      "path": "scene_name.gd",
      "content": "full script content",
      "language": "gdscript"
    }
  ]
}`;
}

function buildWorkerPrompt(prompt: string): string {
  return `You are an expert Cloudflare Workers developer. Generate a complete, working Cloudflare Worker based on the user's request.

User Request:
${prompt}

Requirements:
1. Use TypeScript with proper types
2. Include error handling
3. Add CORS headers
4. Use D1 for database operations if needed
5. Follow Workers best practices
6. Make the code production-ready

Response format: Return a JSON object with this structure:
{
  "description": "Brief description",
  "workerName": "kebab-case-name",
  "files": [
    {
      "path": "src/index.ts",
      "content": "full file content",
      "language": "typescript"
    }
  ]
}`;
}

// ═══════════════════════════════════════════════════════════
// Code Generator Service
// ═══════════════════════════════════════════════════════════

export class CodeGenerator {
  constructor(
    private ai: any,  // Cloudflare AI binding
    private db: D1Database
  ) {}

  /**
   * Generate code based on request
   */
  async generate(request: GenerationRequest, userId?: string): Promise<GenerationResult> {
    const config = MODEL_CONFIGS[request.quality];
    const id = nanoid();

    // Build the prompt based on type
    const systemPrompt = this.getSystemPrompt(request.type, request.prompt);

    // Call AI
    const response = await this.ai.run(config.model, {
      prompt: systemPrompt,
      max_tokens: config.maxTokens,
      temperature: config.temperature
    });

    // Parse AI response
    let generatedFiles: GeneratedFile[];
    try {
      const parsed = JSON.parse(response.response);
      generatedFiles = parsed.files || [];
    } catch {
      // Fallback: create single file from raw response
      generatedFiles = [{
        path: 'generated.txt',
        content: response.response,
        language: 'text'
      }];
    }

    // Calculate work ratio (estimate based on tokens and quality)
    const work_ratio = config.expectedWorkRatio;

    // Store generation record
    await this.db.prepare(`
      INSERT INTO code_generations (
        id, user_id, prompt, model_used, quality_level,
        tokens_generated, work_ratio, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
    `).bind(
      id,
      userId || null,
      request.prompt,
      config.model,
      request.quality,
      response.usage?.total_tokens || 0,
      work_ratio
    ).run();

    // Verify generated code
    const verification = await this.verify(generatedFiles);

    return {
      id,
      type: request.type,
      prompt: request.prompt,
      quality: request.quality,
      model_used: config.model,
      tokens_generated: response.usage?.total_tokens || 0,
      work_ratio,
      code: generatedFiles.map(f => f.content).join('\n\n'),
      files: generatedFiles,
      verified: verification.passed,
      created_at: new Date().toISOString()
    };
  }

  private getSystemPrompt(type: string, prompt: string): string {
    switch (type) {
      case 'theia-extension':
        return buildTheiaExtensionPrompt(prompt);
      case 'godot-scene':
        return buildGodotScenePrompt(prompt);
      case 'worker':
        return buildWorkerPrompt(prompt);
      default:
        return `Generate code for: ${prompt}`;
    }
  }

  /**
   * Verify generated code
   */
  verifyMethod(files: GeneratedFile[]): VerificationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    let testsRun = 0;
    let testsPassed = 0;

    for (const file of files) {
      // Basic syntax checks
      if (file.language === 'typescript') {
        testsRun++;
        if (file.content.includes('export')) {
          testsPassed++;
        } else {
          warnings.push(`${file.path}: Missing exports`);
        }

        // Check for common errors
        if (file.content.includes('TODO') || file.content.includes('FIXME')) {
          warnings.push(`${file.path}: Contains TODO items`);
        }

        if (file.content.includes('any')) {
          warnings.push(`${file.path}: Uses 'any' type`);
        }
      }

      if (file.language === 'gdscript') {
        testsRun++;
        if (file.content.includes('extends ')) {
          testsPassed++;
        } else {
          errors.push(`${file.path}: Missing extends clause`);
        }
      }

      if (file.language === 'gdscene') {
        testsRun++;
        if (file.content.includes('[gd_scene')) {
          testsPassed++;
        } else {
          errors.push(`${file.path}: Invalid scene format`);
        }
      }
    }

    return {
      passed: errors.length === 0,
      errors,
      warnings,
      tests_run: testsRun,
      tests_passed: testsPassed
    };
  }

  /**
   * Async wrapper for verification (for compatibility)
   */
  async verify(files: GeneratedFile[]): Promise<VerificationResult> {
    return this.verifyMethod(files);
  }

  /**
   * Rollback to previous generation
   */
  async rollback(generationId: string): Promise<GenerationResult | null> {
    const previous = await this.db.prepare(`
      SELECT rollback_id FROM code_generations WHERE id = ?
    `).bind(generationId).first();

    if (!previous || !previous.rollback_id) {
      return null;
    }

    return await this.getGeneration(previous.rollback_id as string);
  }

  /**
   * Get generation record
   */
  async getGeneration(id: string): Promise<GenerationResult | null> {
    const record = await this.db.prepare(`
      SELECT * FROM code_generations WHERE id = ?
    `).bind(id).first();

    if (!record) return null;

    return {
      id: record.id as string,
      type: '',  // Would need to parse from prompt
      prompt: record.prompt as string,
      quality: record.quality_level as QualityLevel,
      model_used: record.model_used as string,
      tokens_generated: record.tokens_generated as number,
      work_ratio: record.work_ratio as number,
      code: '',  // Would need to fetch from storage
      files: [],
      verified: record.verified === 1,
      created_at: record.created_at as string
    };
  }

  /**
   * Get user's generation history
   */
  async getHistory(userId: string, limit = 20): Promise<GenerationResult[]> {
    const records = await this.db.prepare(`
      SELECT * FROM code_generations
      WHERE user_id = ?
      ORDER BY created_at DESC
      LIMIT ?
    `).bind(userId, limit).all();

    return (records.results || []).map((r: any) => ({
      id: r.id,
      type: '',
      prompt: r.prompt,
      quality: r.quality_level,
      model_used: r.model_used,
      tokens_generated: r.tokens_generated,
      work_ratio: r.work_ratio,
      code: '',
      files: [],
      verified: r.verified === 1,
      created_at: r.created_at
    }));
  }
}

// ═══════════════════════════════════════════════════════════
// Request Handlers
// ═══════════════════════════════════════════════════════════

export interface CodeGeneratorEnv {
  AI: any;
  STUDENT_STATE: D1Database;
  PROJECT_STORAGE: R2Bucket;
}

export async function handleCodeGeneratorRequest(
  request: Request,
  env: CodeGeneratorEnv,
  _ctx: ExecutionContext
): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname.replace('/api/v1/generate', '');
  const method = request.method;

  const generator = new CodeGenerator(env.AI, env.STUDENT_STATE);

  // CORS
  if (method === 'OPTIONS') {
    return new Response(null, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      }
    });
  }

  try {
    // POST /generate - Generate code
    if (path === '/generate' && method === 'POST') {
      const data = await request.json() as GenerationRequest;
      const userId = request.headers.get('X-User-Id') || undefined;

      const result = await generator.generate(data, userId);

      return Response.json(result, { status: 201 });
    }

    // GET /history - Get user's generation history
    if (path === '/history' && method === 'GET') {
      const userId = request.headers.get('X-User-Id');
      if (!userId) {
        return Response.json({ error: 'Missing user ID' }, { status: 401 });
      }

      const limit = url.searchParams.get('limit')
        ? parseInt(url.searchParams.get('limit')!)
        : 20;

      const history = await generator.getHistory(userId, limit);

      return Response.json({ generations: history });
    }

    // POST /verify/:id - Verify a generation
    if (path.match(/\/verify\/[^/]+$/) && method === 'POST') {
      // Get the generation files and verify
      // This is simplified - would need to fetch files from R2
      const verification = await generator.verify([]);

      return Response.json(verification);
    }

    // POST /rollback/:id - Rollback to previous version
    if (path.match(/\/rollback\/[^/]+$/) && method === 'POST') {
      const id = path.split('/').pop()!;

      const previous = await generator.rollback(id);

      if (!previous) {
        return Response.json({ error: 'No previous version found' }, { status: 404 });
      }

      return Response.json(previous);
    }

    return Response.json({ error: 'Not found' }, { status: 404 });

  } catch (error: any) {
    return Response.json({
      error: error.message || 'Internal server error'
    }, { status: 500 });
  }
}
